[phases.setup]
nixPkgs = ["nodejs_24", "libuuid", "chromium"]
nixpkgsArchive = "9259541b1652dae633707ff840858fd397df66bc"
aptPkgs = ["fonts-liberation"]

[variables]
PUPPETEER_SKIP_DOWNLOAD = "true"
PUPPETEER_EXECUTABLE_PATH = "/root/.nix-profile/bin/chromium"

[phases.install]
cmds = ["PUPPETEER_SKIP_DOWNLOAD=true npm ci"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"
